[package]
name = "rusty_chess"
version = "0.1.0"
edition = "2021"

[features]
bitboard_generator = []


[dependencies]
chess = "3.2.0"
speedy2d = "1.12.0"
futures = { version = "0.3", features = ["async-await"] }
